services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "../wait-for-it.sh &&
         gunicorn projeto_api.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    working_dir: /app/projeto_api
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
      - bridge_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    command: npm start -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - bridge_network

  database:
    image: mysql:latest
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - bridge_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  bridge_network:
    driver: bridge

volumes:
  mysql_data:
